### ISSUE TITLE
Bug: Comments are treated as value

### ISSUE THREAD

**Issue by sonulohani** [mcmtroffaes/inipp#15]
Hi,

I've just modified the **test1.ini** file to

```ini
[section] 
variable="value" ;dummy
```

Output in **test1.output** should be 
```
>>> ERRORS <<<
>>> GENERATE <<<
[section]
variable=value

>>> INTERPOLATE <<<
[section]
variable=value
```

However the output from the library is:
```
>>> ERRORS <<<
>>> GENERATE <<<
[section]
variable=value ;dummy

>>> INTERPOLATE <<<
[section]
variable=value ;dummy


```

**Comment by mcmtroffaes** [comment]
Only standard ini comments (";" at the start of the line) are supported (to keep the implementation as simple as possible):

https://en.wikipedia.org/wiki/INI_file#Comments

**Comment by sonulohani** [comment]
However wiki doesn't define the standards. The example that I have described in the issue description is a valid ini file.

**Comment by mcmtroffaes** [comment]
Indeed, there's no standard for ini files. There's a reason a lot of standard implementations only support comments at the start of a line, and that's because semi-colons aren't that unusual as characters in values.

One way to support them would be to have an extra function that strip comments from values after parsing, similar to how default sections and interpolation currently work.

**Comment by sonulohani** [comment]
Since there is no standard so closing issue.

**Comment by mcmtroffaes** [comment]
I've added a ``strip_trailing_comments`` function as suggested. Just call it right after parsing if you need this feature.
