### ISSUE TITLE
why errors in Ini class are stored in a list?

### ISSUE THREAD

**Issue by v1otusc** [mcmtroffaes/inipp#29]
Why use this container type?

**Comment by mcmtroffaes** [comment]
Thanks for reaching out. However, I'm confused by your report. Can you provide full details as to how to reproduce the specific problem you're having with inipp, along with any potential solutions?

**Comment by v1otusc** [comment]
@mcmtroffaes  Thanks for the reply! haven't had a problem so far, but just curious about the datatype of errors, one of member variable of class Ini:

```c++
template<class CharT>
class Ini
{
public:
	using String = std::basic_string<CharT>;
	using Section = std::map<String, String>;
	using Sections = std::map<String, Section>;

	Sections sections;
	std::list<String> errors;
	std::shared_ptr<Format<CharT>> format;
```

Any particular benefit?

**Comment by mcmtroffaes** [comment]
Ah, the right place to discuss C++ datatypes would be some forum or discord rather than this issue tracker, whence I'll close this now. That said, I can give you some starting pointers:

https://stackoverflow.com/questions/2209224/vector-vs-list-in-stl
https://stackoverflow.com/questions/10699265/how-can-i-efficiently-select-a-standard-library-container-in-c11

I hope you find this helpful!
