### ISSUE TITLE
Support comments behind a line

### ISSUE THREAD

**Issue by JanVerschaeren** [mcmtroffaes/inipp#3]
Hey,

You don' support comments behind a line yet.
Example:

[general]
some_field = some_value      ; Comment

**Comment by JanVerschaeren** [comment]
But luckily i have a fix that works and follows your way of coding:
`
template <class CharT>
inline void delete_after_character(std::basic_string<CharT> & s, CharT c) {
	s.erase(std::find(s.begin(), s.end(), c), s.end());
}`

Then you can just before you trim the lines put:
`detail::delete_after_character(line, char_comment)`

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Unfortunately, some ini files may use semi-colons to separate values (this is quite common in windows, e.g. to specify the PATH variable). Quoting from https://en.wikipedia.org/wiki/INI_file: "The value can contain any character." So yes, comments behind a line are not supported, and this is intentional, to allow all possible value strings to be specified with no restriction on characters.

If you really need to rely on such non-standard feature, you could process your file contents to remove also all inline comments, before passing it to the parser.

**Comment by mcmtroffaes** [comment]
Just to note here that there's now a function that does this, see https://github.com/mcmtroffaes/inipp/commit/b0ed71eadc6f44c582f1ff16ff2f65900f82e027
